[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"
uvicorn = {extras = ["standart"], version = "^0.34.2"}
pydantic = {extras = ["email"], version = "^2.11.4"}
pydantic-settings = "^2.9.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.41"}
mysqlclient = "^2.2.7"
pymysql = "^1.1.1"
asyncmy = "^0.2.10"
alembic = "^1.16.1"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

