"""update users table

Revision ID: 46f634387068
Revises: 6cb255614b36
Create Date: 2025-05-25 15:15:13.799882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f634387068'
down_revision: Union[str, None] = '6cb255614b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foo', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bar', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_foo_bar'), 'users', ['foo', 'bar'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_foo_bar'), 'users', type_='unique')
    op.drop_column('users', 'bar')
    op.drop_column('users', 'foo')
    # ### end Alembic commands ###
